### ISSUE TITLE
Error at Create ToDo

### ISSUE THREAD

**Issue by Paptoos** [KomeilParseh/TITA-DO#3]
Hello
I am Amirmohammad Ghazi and I test this app
but when I add a todo , write name , description , user , date and time , and click save have this error :
![image](https://user-images.githubusercontent.com/72940447/103453781-b658c680-4cf2-11eb-903c-ebf3332a7a44.png)

**Comment by KomeilParseh** [comment]
سلام امیرحسین جان ببخشید در دستگاهی هستم که دستم به هر جا میخوره .
آیا شما دیتا بیس رو ساختید ؟ منظور اینکه طبق راهنما پیشرفتید؟

**Comment by KomeilParseh** [comment]
من الان تست کردم مشکلی نیستش احتمالا مرحله ای از راه اندازی رو اشتباه رفتید البته امیدوارم :)

**Comment by KomeilParseh** [comment]
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/65954744/103455823-a1396300-4d05-11eb-99fc-6fd4f5b505dc.gif)

### به این شکل الان امتحان کردم

**Comment by Paptoos** [comment]
در لیست کار ها ساخت دیتابیس نبود !

**Comment by KomeilParseh** [comment]
منظور اینه:
`python manage.py makemigrations`


`python manage.py migrate`
احتمال میدم که یادتون رفته یه بار دیگه پروژه رو کلون کنید تغییراتی اعمال کردم فقط لطفا دوباره به ترتیب مراحل رو اجرا کنید

**Comment by Paptoos** [comment]
دوباره تست خواهم کرد ، ممنون

**Comment by KomeilParseh** [comment]
حل شد آیا؟
